use_frameworks!

target 'MAGNSAttributedStringFormat_Example' do
  pod 'MAGNSAttributedStringFormat', '~> 0.2.1'

  target 'MAGNSAttributedStringFormat_Tests' do
    inherit! :search_paths

    
  end
end
